# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9dac96a42524109d37c25141fcdfa3f34b52b64ccff30fa4bae0be396d44164a0e67b9ed8a13570ea44a8df1cf64be906f4caeb09b2dbabf126fd0e48eca37e9

test:
  secret_key_base: b4883de1e17bcc0bd895cf1efd2eaff3b581d424e0c562adb88bd7844c844a1a3cb3ef11fe27e38e1bf20c4e501c2fac16e53b02f29d1d17f5ef23949cded327

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
