-- remove any records and start the id sequence back to 1
TRUNCATE TABLE houses RESTART IDENTITY CASCADE;
TRUNCATE TABLE spells_students RESTART IDENTITY CASCADE;
TRUNCATE TABLE spells RESTART IDENTITY CASCADE;
TRUNCATE TABLE students RESTART IDENTITY CASCADE;
TRUNCATE TABLE death_eater_memberships RESTART IDENTITY CASCADE;

-- create houses
INSERT INTO houses
  (name)
VALUES
  ('Gryffindor'),
  ('Hufflepuff'),
  ('Ravenclaw'),
  ('Slytherin');

-- create spells
INSERT INTO spells
  (name)
VALUES
  ('Accio'),
  ('Wingardium Leviosa'),
  ('Lumos'),
  ('Avada Kedavra');

-- create students
INSERT INTO students
 (fname, lname, house_id)
VALUES
  ('Euan', 'Abercrombie', 1),
  ('Katie', 'Bell', 1),
  ('Sirius', 'Black', 1),
  ('Lavender', 'Brown', 1),
  ('Ritchie', 'Coote', 1),
  ('Colin', 'Creevey', 1),
  ('Dennis', 'Creevey', 1),
  ('Albus', 'Dumbledore', 1),
  ('Seamus', 'Finnigan', 1),
  ('Hermione', 'Granger', 1),
  ('Rubeus', 'Hagrid', 1),
  ('Angelina', 'Johnson', 1),
  ('Lee', 'Jordan', 1),
  ('Andrew', 'Kirke', 1),
  ('Neville', 'Longbottom', 1),
  ('Remus', 'Lupin', 1),
  ('Natalie', 'McDonald', 1),
  ('Mary', 'Macdonald', 1),
  ('Minerva', 'McGonagall', 1),
  ('Cormac', 'McLaggen', 1),
  ('Parvati', 'Patil', 1),
  ('Jimmy', 'Peakes', 1),
  ('Peter', 'Pettigrew', 1),
  ('Harry', 'Potter', 1),
  ('James', 'Potter', 1),
  ('Lily', 'Potter', 1),
  ('Demelza', 'Robins', 1),
  ('Jack', 'Sloper', 1),
  ('Alicia', 'Spinnet', 1),
  ('Dean', 'Thomas', 1),
  ('Romilda', 'Vane', 1),
  ('Arthur', 'Weasley', 1),
  ('Bill', 'Weasley', 1),
  ('Charlie', 'Weasley', 1),
  ('Fred', 'Weasley', 1),
  ('George', 'Weasley', 1),
  ('Ginny', 'Weasley', 1),
  ('Molly', 'Weasley', 1),
  ('Percy', 'Weasley', 1),
  ('Ron', 'Weasley', 1),
  ('Oliver', 'Wood', 1),
  ('Hannah', 'Abbott', 2),
  ('Susan', 'Bones', 2),
  ('Eleanor', 'Branstone', 2),
  ('Owen', 'Cauldwell', 2),
  ('Cedric', 'Diggory', 2),
  ('Justin', 'Finch-Fletchley', 2),
  ('Ernie', 'Macmillan', 2),
  ('Laura', 'Madley', 2),
  ('Eloise', 'Midgeon', 2),
  ('Zacharias', 'Smith', 2),
  ('Pomona', 'Sprout', 2),
  ('Nymphadora', 'Tonks', 2),
  ('Kevin', 'Whitby', 2),
  ('Rose', 'Zeller', 2),
  ('Stewart', 'Ackerley', 3),
  ('Marcus', 'Belby', 3),
  ('Terry', 'Boot', 3),
  ('Mandy', 'Brocklehurst', 3),
  ('Cho', 'Chang', 3),
  ('Eddie', 'Carmichael', 3),
  ('Penelope', 'Clearwater', 3),
  ('Michael', 'Corner', 3),
  ('Roger', 'Davies', 3),
  ('Marietta', 'Edgecombe', 3),
  ('S', 'Fawcett', 3),
  ('Filius', 'Flitwick', 3),
  ('Anthony', 'Goldstein', 3),
  ('Luna', 'Lovegood', 3),
  ('Padma', 'Patil', 3),
  ('Orla', 'Quirke', 3),
  ('Lisa', 'Turpin', 3),
  ('Malcolm', 'Baddock', 4),
  ('Regulus', 'Black', 4),
  ('Miles', 'Bletchley', 4),
  ('Millicent', 'Bullstrode', 4),
  ('Vincent', 'Crabbe', 4),
  ('Marcus', 'Flint', 4),
  ('Gregory', 'Goyle', 4),
  ('Terence', 'Higgs', 4),
  ('Bellatrix', 'Lestrange', 4),
  ('Rabastan', 'Lestrange', 4),
  ('Rodolphus', 'Lestrange', 4),
  ('Abraxas', 'Malfoy', 4),
  ('Draco', 'Malfoy', 4),
  ('Lucius', 'Malfoy', 4),
  ('Narcissa', 'Malfoy', 4),
  ('Theodore', 'Nott', 4),
  ('Pansy', 'Parkinson', 4),
  ('Graham', 'Pritchard', 4),
  ('Adrian', 'Pucey', 4),
  ('Tom', 'Riddle', 4),
  ('Horace', 'Slughorn', 4),
  ('Severus', 'Snape', 4),
  ('Blaise', 'Zabini', 4),
  ('Godric', 'Gryffindor', 1),
  ('Helga', 'Hufflepuff', 2),
  ('Rowena', 'Ravenclaw', 3),
  ('Salazar', 'Slytherin', 4);

-- create death eater memberships
INSERT INTO death_eater_memberships
  (joined_on, student_id)
VALUES
  ('now', 23),
  ('now', 74),
  ('now', 81),
  ('now', 85),
  ('now', 86),
  ('now', 94);

-- teach every student "accio"
INSERT INTO spells_students
  (spell_id, student_id)
VALUES
  (1, 1),
  (1, 2),
  (1, 3),
  (1, 4),
  (1, 5),
  (1, 6),
  (1, 7),
  (1, 8),
  (1, 9),
  (1, 10),
  (1, 11),
  (1, 12),
  (1, 13),
  (1, 14),
  (1, 15),
  (1, 16),
  (1, 17),
  (1, 18),
  (1, 19),
  (1, 20),
  (1, 21),
  (1, 22),
  (1, 23),
  (1, 24),
  (1, 25),
  (1, 26),
  (1, 27),
  (1, 28),
  (1, 29),
  (1, 30),
  (1, 31),
  (1, 32),
  (1, 33),
  (1, 34),
  (1, 35),
  (1, 36),
  (1, 37),
  (1, 38),
  (1, 39),
  (1, 40),
  (1, 41),
  (1, 42),
  (1, 43),
  (1, 44),
  (1, 45),
  (1, 46),
  (1, 47),
  (1, 48),
  (1, 49),
  (1, 50),
  (1, 51),
  (1, 52),
  (1, 53),
  (1, 54),
  (1, 55),
  (1, 56),
  (1, 57),
  (1, 58),
  (1, 59),
  (1, 60),
  (1, 61),
  (1, 62),
  (1, 63),
  (1, 64),
  (1, 65),
  (1, 66),
  (1, 67),
  (1, 68),
  (1, 69),
  (1, 70),
  (1, 71),
  (1, 72),
  (1, 73),
  (1, 74),
  (1, 75),
  (1, 76),
  (1, 77),
  (1, 78),
  (1, 79),
  (1, 80),
  (1, 81),
  (1, 82),
  (1, 83),
  (1, 84),
  (1, 85),
  (1, 86),
  (1, 87),
  (1, 88),
  (1, 89),
  (1, 90),
  (1, 91),
  (1, 92),
  (1, 93),
  (1, 94),
  (1, 95),
  (1, 96),
  (1, 97),
  (1, 98),
  (1, 99);


-- allow each slytherin to do Avada Kedavra
INSERT INTO spells_students
  (student_id, spell_id)
VALUES
  (74, 4),
  (75, 4),
  (76, 4),
  (77, 4),
  (78, 4),
  (79, 4),
  (80, 4),
  (81, 4),
  (82, 4),
  (83, 4),
  (84, 4),
  (85, 4),
  (86, 4),
  (87, 4),
  (88, 4),
  (89, 4),
  (90, 4),
  (91, 4),
  (92, 4),
  (93, 4),
  (94, 4),
  (95, 4),
  (96, 1),
  (97, 2),
  (98, 3),
  (99, 4);
