TRUNCATE TABLE students RESTART IDENTITY CASCADE;

INSERT INTO students
 (fname, lname, house_id)
VALUES
  ('Euan', 'Abercrombie', 1),
  ('Katie', 'Bell', 1),
  ('Sirius', 'Black', 1),
  ('Lavender', 'Brown', 1),
  ('Ritchie', 'Coote', 1),
  ('Colin', 'Creevey', 1),
  ('Dennis', 'Creevey', 1),
  ('Albus', 'Dumbledore', 1),
  ('Seamus', 'Finnigan', 1),
  ('Hermione', 'Granger', 1),
  ('Rubeus', 'Hagrid', 1),
  ('Angelina', 'Johnson', 1),
  ('Lee', 'Jordan', 1),
  ('Andrew', 'Kirke', 1),
  ('Neville', 'Longbottom', 1),
  ('Remus', 'Lupin', 1),
  ('Natalie', 'McDonald', 1),
  ('Mary', 'Macdonald', 1),
  ('Minerva', 'McGonagall', 1),
  ('Cormac', 'McLaggen', 1),
  ('Parvati', 'Patil', 1),
  ('Jimmy', 'Peakes', 1),
  ('Peter', 'Pettigrew', 1),
  ('Harry', 'Potter', 1),
  ('James', 'Potter', 1),
  ('Lily', 'Potter', 1),
  ('Demelza', 'Robins', 1),
  ('Jack', 'Sloper', 1),
  ('Alicia', 'Spinnet', 1),
  ('Dean', 'Thomas', 1),
  ('Romilda', 'Vane', 1),
  ('Arthur', 'Weasley', 1),
  ('Bill', 'Weasley', 1),
  ('Charlie', 'Weasley', 1),
  ('Fred', 'Weasley', 1),
  ('George', 'Weasley', 1),
  ('Ginny', 'Weasley', 1),
  ('Molly', 'Weasley', 1),
  ('Percy', 'Weasley', 1),
  ('Ron', 'Weasley', 1),
  ('Oliver', 'Wood', 1),
  ('Hannah', 'Abbott', 2),
  ('Susan', 'Bones', 2),
  ('Eleanor', 'Branstone', 2),
  ('Owen', 'Cauldwell', 2),
  ('Cedric', 'Diggory', 2),
  ('Justin', 'Finch-Fletchley', 2),
  ('Ernie', 'Macmillan', 2),
  ('Laura', 'Madley', 2),
  ('Eloise', 'Midgeon', 2),
  ('Zacharias', 'Smith', 2),
  ('Pomona', 'Sprout', 2),
  ('Nymphadora', 'Tonks', 2),
  ('Kevin', 'Whitby', 2),
  ('Rose', 'Zeller', 2),
  ('Stewart', 'Ackerley', 3),
  ('Marcus', 'Belby', 3),
  ('Terry', 'Boot', 3),
  ('Mandy', 'Brocklehurst', 3),
  ('Cho', 'Chang', 3),
  ('Eddie', 'Carmichael', 3),
  ('Penelope', 'Clearwater', 3),
  ('Michael', 'Corner', 3),
  ('Roger', 'Davies', 3),
  ('Marietta', 'Edgecombe', 3),
  ('S', 'Fawcett', 3),
  ('Filius', 'Flitwick', 3),
  ('Anthony', 'Goldstein', 3),
  ('Luna', 'Lovegood', 3),
  ('Padma', 'Patil', 3),
  ('Orla', 'Quirke', 3),
  ('Lisa', 'Turpin', 3),
  ('Malcolm', 'Baddock', 4),
  ('Regulus', 'Black', 4),
  ('Miles', 'Bletchley', 4),
  ('Millicent', 'Bullstrode', 4),
  ('Vincent', 'Crabbe', 4),
  ('Marcus', 'Flint', 4),
  ('Gregory', 'Goyle', 4),
  ('Terence', 'Higgs', 4),
  ('Bellatrix', 'Lestrange', 4),
  ('Rabastan', 'Lestrange', 4),
  ('Rodolphus', 'Lestrange', 4),
  ('Abraxas', 'Malfoy', 4),
  ('Draco', 'Malfoy', 4),
  ('Lucius', 'Malfoy', 4),
  ('Narcissa', 'Malfoy', 4),
  ('Theodore', 'Nott', 4),
  ('Pansy', 'Parkinson', 4),
  ('Graham', 'Pritchard', 4),
  ('Adrian', 'Pucey', 4),
  ('Tom', 'Riddle', 4),
  ('Horace', 'Slughorn', 4),
  ('Severus', 'Snape', 4),
  ('Blaise', 'Zabini', 4),
  ('Godric', 'Gryffindor', 1),
  ('Helga', 'Hufflepuff', 2),
  ('Rowena', 'Ravenclaw', 3),
  ('Salazar', 'Slytherin', 4);

INSERT INTO death_eater_memberships
  (joined_on, student_id)
VALUES
  ('now', 23),
  ('now', 74),
  ('now', 81),
  ('now', 85),
  ('now', 86),
  ('now', 94);
