# A sample Gemfile
source "https://rubygems.org"

ruby "2.1.0"

gem 'sinatra', '1.4.5'
gem 'sinatra-contrib'
gem 'rest-client'
gem 'redcarpet'

group :development do
  gem 'pry'
  gem 'awesome_print'
end